export const API_ROUTES = {
    // FETCH_DATA: 'tmb-count?field=carrier&value=Telstra Mobile Broadband (Consumer)',
    FETCH_DATA:'data-by-store',
    GET_ALL:'get-all',
    CREATE_TARGET: '/target',
  GET_TARGET: 'target',
  UPDATE_TARGET: '/target',
  DELETE_TARGET: '/delete-target',
  CREATE_ADMIN: '/admin',
  ALL_ADMIN:'/all-admin',
  LOGIN:'/login',
  CREATE_NPS:'/nps',
  GET_NPS:'/nps/all',
  UPDATE_NPS:'/nps',
  CREATE_KPI:'/kpi',
  GET_KPI:'/kpi',
  UPDATE_KPI:'/kpi',
  GET_COMMISSION:'/getcomission',
  CREATE_COMMISSION:'/createcommission',
  UPDATE_COMMISSION:'/updatecommission',
  CREATE_PRORATA_STAFF:'/prorata-staff',
  GET_PRORATA_STAFF:'/prorata-staff',
  UPDATE_PRORATA_STAFF:'/prorata-staff',
  DELETE_PRORATA_STAFF:'/prorata-staff',
  SYNC_STAFF:'/staff/sync',
  GET_ALL_STAFF:'/staff/all',
  GET_STAFF_BY_LOCATION:'/staff',
  ADD_STAFF:'/staff',
  UPDATE_STAFF:'/staff',
  DELETE_STAFF:'/staff',
    // Add more routes here as needed
  };